services:
  server:
    env_file: ".env"
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "node", "server.js"]

  db:
    env_file: ".env"
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./sql_initialize/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    ports:
      - "3307:3306"  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 50s
      retries: 5
volumes:
  db-data: 