services:
  server:
    env_file: ".env"
    build:
      context: .
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app/

  db:
    env_file: ".env"
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./sql_initialize/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    ports:
      - "3307:3306"  
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 100s
      retries: 10
volumes:
  db-data: 