name: E2E Tests

on:
    push:
        branches: [69-deploy-the-site]

    workflow_dispatch:

jobs:
    e2e-tests:
        runs-on: ubuntu-latest

        timeout-minutes: 15

        steps:
            - name: Checkout
              uses: actions/checkout

            - name: Start local environment with Docker Compose
              run: docker compose up -d

            - name: Build E2E Docker image
              working-directory: e2e
              run: docker build -t playwright-tests .

            - name: Run E2E tests
              working-directory: e2e
              run: docker run --name playwright-tests --network=host playwright-tests npm run e2etest
