name: E2E Tests

on:
    push:
        branches: []

jobs:
    e2e-tests:
        runs-on: ubuntu-latest

        timeout-minutes: 15

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Start local environment with Docker Compose
              run: docker compose up -d

            - name: Playwright install
              working-directory: e2e
              run: |
                  npm ci
                  npx playwright install-deps
                  npx playwright install

            - name: Playwright run
              working-directory: e2e
              run: |
                  npm run e2etest

            # - name: Build E2E Docker image
            #   working-directory: e2e
            #   run: docker build -t playwright-tests .

            # - name: Run E2E tests
            #   working-directory: e2e
            #   run: docker run --name playwright-tests --network=host playwright-tests npm run e2etest
